services:
  indicatoreye:
    image: ghcr.io/steffjenl/indicatoreye:${RELEASE_VERSION:-latest}
    build: .
    container_name: indicatoreye
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
